development:
  database: project
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db
test:
  database: project_test
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db
